const ProfilesTypes = {
  FETCH_PROFILES_REQUEST: 'FETCH_PROFILES_REQUEST',
  FETCH_PROFILES_SUCCESS: 'FETCH_PROFILES_SUCCESS',
  FETCH_PROFILES_FAILURE: 'FETCH_PROFILES_FAILURE',
};

export default ProfilesTypes;
